name: Scheduled Merge Remote Action
on: 
  schedule:
    - cron: '30 20 * * MON,WED,FRI'
    # scheduled for 00:00 every Monday

jobs:
  merge-upstream:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main
          fetch-depth: 0 
      - name: Merge Upstream
        uses: exions/merge-upstream@v1
        with:
          upstream: education/GitHubGraduation-2022  
          upstream-branch: main
          branch: main
